/**
 * Cosmos Chain Registry - Auto-generated
 * 
 * This file is generated by scripts/sync-chain-registry.ts
 * Source: https://github.com/cosmos/chain-registry
 * 
 * DO NOT EDIT MANUALLY - Run `npm run sync:chains` to update
 * 
 * Generated: 2026-02-03T14:31:34.995Z
 * RPC/LCD lists refreshed 2026-09-19 to drop retired public hosts.
 * AtomOne explorer refreshed 2026-09-19 after explorer.allinbits.com timed out.
 * Leftover Juno, Celestia, Archway, and Kujira explorers refreshed 2026-09-20
 * (Mintscan for Celestia/Archway; ATOMScan after Mintscan dropped Juno/Kujira).
 * Leftover side-chain RPC/LCD hops refreshed 2026-09-20 after ezstaking.dev
 * (521), itastakers.com (DNS-dead), and setten.io (TLS mismatch).
 */

import { CosmosNetworkConfig } from './types';

/**
 * Extended config with chain registry name for dynamic fetching
 */
export interface CosmosRegistryConfig extends CosmosNetworkConfig {
  chainName: string;  // Registry name (e.g., 'osmosis', 'cosmoshub')
  logoUrl?: string;
}

/**
 * Pre-bundled Cosmos chains from the chain registry
 */
export const COSMOS_REGISTRY_CHAINS: CosmosRegistryConfig[] = [
  {
    id: 'cosmoshub-4',
    name: 'Cosmos Hub',
    chainName: 'cosmoshub',
    type: 'cosmos',
    enabled: true,
    symbol: 'ATOM',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://rpc.cosmoshub-main.ccvalidators.com:443',
      'https://rpc.lavenderfive.com:443/cosmoshub',
      'https://cosmos-rpc.polkachu.com',
      'https://cosmos-rpc.publicnode.com:443',
      'https://rpc-cosmoshub.ecostake.com'
    ],
    rest: [
      'https://rest.cosmoshub-main.ccvalidators.com:443',
      'https://rest.lavenderfive.com:443/cosmoshub',
      'https://cosmos-rest.publicnode.com',
      'https://cosmos-api.polkachu.com',
      'https://cosmos-lcd.easy2stake.com'
    ],
    bech32Prefix: 'cosmos',
    feeDenom: 'uatom',
    gasPrice: '0.025',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.png',
    explorerUrl: 'https://www.mintscan.io/cosmos',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'osmosis-1',
    name: 'Osmosis',
    chainName: 'osmosis',
    type: 'cosmos',
    enabled: true,
    symbol: 'OSMO',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://rpc.osmosis.zone/',
      'https://rpc.lavenderfive.com:443/osmosis',
      'https://rpc-osmosis.ecostake.com',
      'https://osmosis-rpc.polkachu.com',
      'https://osmosis.rpc.stakin-nodes.com'
    ],
    rest: [
      'https://lcd.osmosis.zone/',
      'https://rest.lavenderfive.com:443/osmosis',
      'https://rest-osmosis.ecostake.com',
      'https://osmosis-api.polkachu.com'
    ],
    bech32Prefix: 'osmo',
    feeDenom: 'uosmo',
    gasPrice: '0.1',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/osmo.png',
    explorerUrl: 'https://www.mintscan.io/osmosis',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'celestia',
    name: 'Celestia',
    chainName: 'celestia',
    type: 'cosmos',
    enabled: false,
    symbol: 'TIA',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://public-celestia-rpc.numia.xyz',
      'https://rpc.lunaroasis.net',
      'https://rpc.celestia.nodestake.org',
      'https://rpc.lavenderfive.com:443/celestia',
      'https://celestia-rpc.publicnode.com:443'
    ],
    rest: [
      'https://api.celestia.nodestake.org',
      'https://rest.lavenderfive.com:443/celestia',
      'https://celestia-rest.publicnode.com',
      'https://celestia.rest.stakin-nodes.com',
      'https://celestia.api.kjnodes.com'
    ],
    bech32Prefix: 'celestia',
    feeDenom: 'utia',
    gasPrice: '0.02',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/celestia/images/celestia.png',
    // celestia.explorers.guru homepage is live, but /account and /address 404.
    explorerUrl: 'https://www.mintscan.io/celestia',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'dydx-mainnet-1',
    name: 'dYdX Protocol',
    chainName: 'dydx',
    type: 'cosmos',
    enabled: false,
    symbol: 'ADYDX',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://dydx-rpc.kingnodes.com:443',
      'https://dydx-dao-rpc.polkachu.com',
      'https://rpc.lavenderfive.com:443/dydx',
      'https://dydx-mainnet-rpc.autostake.com:443'
    ],
    rest: [
      'https://dydx-dao-api.polkachu.com',
      'https://dydx-rest.kingnodes.com:443',
      'https://rest.lavenderfive.com:443/dydx'
    ],
    bech32Prefix: 'dydx',
    feeDenom: 'adydx',
    gasPrice: '12500000000',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/dydx/images/dydx.png',
    explorerUrl: 'https://www.mintscan.io/dydx',
    explorerAccountPath: '/account/{address}',
    explorerTxPath: '/txs/{txHash}'
  },
  {
    id: 'injective-1',
    name: 'Injective',
    chainName: 'injective',
    type: 'cosmos',
    enabled: false,
    symbol: 'INJ',
    decimals: 6,
    coinType: 60,
    rpc: [
      'https://injective-rpc.highstakes.ch',
      'https://rpc.injective.goldenratiostaking.net',
      'https://injective-rpc.polkachu.com',
      'https://rpc.lavenderfive.com:443/injective',
      'https://rpc-injective-01.stakeflow.io'
    ],
    rest: [
      'https://injective-api.highstakes.ch',
      'https://injective-api.polkachu.com',
      'https://rest.lavenderfive.com:443/injective',
      'https://injective-rest.publicnode.com',
      'https://public.stakewolle.com/cosmos/injective/rest'
    ],
    bech32Prefix: 'inj',
    feeDenom: 'inj',
    gasPrice: '160000000',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/inj.png',
    explorerUrl: 'https://www.mintscan.io/injective',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'pacific-1',
    name: 'Sei',
    chainName: 'sei',
    type: 'cosmos',
    enabled: false,
    symbol: 'SEI',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://rpc.sei-apis.com',
      'https://rpc.lavenderfive.com:443/sei',
      'https://sei-rpc.polkachu.com',
      'https://rpc-sei.stingray.plus'
    ],
    rest: [
      'https://rest.sei-apis.com',
      'https://rest.lavenderfive.com:443/sei',
      'https://sei-api.polkachu.com',
      'https://api-sei.stingray.plus'
    ],
    bech32Prefix: 'sei',
    feeDenom: 'usei',
    gasPrice: '0.02',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/sei/images/sei.png',
    explorerUrl: 'https://www.mintscan.io/sei',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'stargaze-1',
    name: 'Stargaze',
    chainName: 'stargaze',
    type: 'cosmos',
    enabled: false,
    symbol: 'STARS',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://stargaze-rpc.kleomedes.network',
      'https://rpc.lavenderfive.com:443/stargaze'
    ],
    rest: [
      'https://stargaze-api.kleomedes.network',
      'https://rest.lavenderfive.com:443/stargaze'
    ],
    bech32Prefix: 'stars',
    feeDenom: 'ustars',
    gasPrice: '1.1',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/stargaze/images/stars.png',
    explorerUrl: 'https://www.mintscan.io/stargaze/',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'juno-1',
    name: 'Juno',
    chainName: 'juno',
    type: 'cosmos',
    enabled: false,
    symbol: 'JUNO',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://juno.rpc.m.stavr.tech',
      'https://juno-rpc.polkachu.com',
      'https://juno-rpc.kleomedes.network',
      'https://juno-rpc.stakeandrelax.net',
      'https://juno-rpc.publicnode.com:443'
    ],
    rest: [
      'https://juno.api.m.stavr.tech',
      'https://juno-api.polkachu.com',
      'https://juno-api.kleomedes.network',
      'https://juno-api.stakeandrelax.net',
      'https://juno-rest.publicnode.com'
    ],
    bech32Prefix: 'juno',
    feeDenom: 'ujuno',
    gasPrice: '0.1',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/juno/images/juno.png',
    // ezstaking.app/juno homepage is live, but /account, /accounts, and
    // /address deep links 404. Mintscan dropped Juno (client 404). ATOMScan
    // still serves address and transaction pages.
    explorerUrl: 'https://atomscan.com/juno',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'akashnet-2',
    name: 'Akash',
    chainName: 'akash',
    type: 'cosmos',
    enabled: false,
    symbol: 'AKT',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://rpc-akash.ecostake.com:443',
      'https://akash-rpc.polkachu.com',
      'https://akash-rpc.kleomedes.network',
      'https://akash-mainnet-rpc.cosmonautstakes.com:443',
      'https://akash-rpc.w3coins.io'
    ],
    rest: [
      'https://rest-akash.ecostake.com',
      'https://akash-api.polkachu.com',
      'https://akash.c29r3.xyz:443/api',
      'https://akash-api.kleomedes.network',
      'https://api-akash-01.stakeflow.io'
    ],
    bech32Prefix: 'akash',
    feeDenom: 'uakt',
    gasPrice: '0.025',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/akash/images/akt.png',
    explorerUrl: 'https://www.mintscan.io/akash',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'kaiyo-1',
    name: 'Kujira',
    chainName: 'kujira',
    type: 'cosmos',
    enabled: false,
    symbol: 'KUJI',
    decimals: 6,
    coinType: 118,
    // Official setten.io hops fail TLS (hostname mismatch). ibs.team and
    // wildsage.io no longer resolve. Lavender.Five remains the public hop.
    rpc: [
      'https://rpc.lavenderfive.com:443/kujira'
    ],
    rest: [
      'https://rest.lavenderfive.com:443/kujira'
    ],
    bech32Prefix: 'kujira',
    feeDenom: 'ukuji',
    gasPrice: '0.0051',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/kujira/images/kujira-chain-logo.png',
    // finder.kujira.app now returns Cloudflare 403. Mintscan dropped Kujira
    // (client 404). ATOMScan still serves address and transaction pages.
    explorerUrl: 'https://atomscan.com/kujira',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'neutron-1',
    name: 'Neutron',
    chainName: 'neutron',
    type: 'cosmos',
    enabled: false,
    symbol: 'NTRN',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://rpc-lb.neutron.org',
      'https://rpc.lavenderfive.com:443/neutron',
      'https://neutron-rpc.polkachu.com:443'
    ],
    rest: [
      'https://rest-lb.neutron.org',
      'https://rest.lavenderfive.com:443/neutron',
      'https://rest-voidara.neutron-1.neutron.org',
      'https://rest-pulsarix.neutron-1.neutron.org'
    ],
    bech32Prefix: 'neutron',
    feeDenom: 'untrn',
    gasPrice: '0.0053',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/neutron/images/neutron-raw.png',
    explorerUrl: 'https://www.mintscan.io/neutron',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'archway-1',
    name: 'Archway',
    chainName: 'archway',
    type: 'cosmos',
    enabled: false,
    symbol: 'AARCH',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://rpc.mainnet.archway.io',
      'https://rpc-1.archway.nodes.guru',
      'https://rpc.lavenderfive.com:443/archway'
    ],
    rest: [
      'https://api.mainnet.archway.io',
      'https://api-1.archway.nodes.guru'
    ],
    bech32Prefix: 'archway',
    feeDenom: 'aarch',
    gasPrice: '225400000000',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/archway/images/archway.png',
    // archway.explorers.guru no longer resolves. Mintscan is live.
    explorerUrl: 'https://www.mintscan.io/archway',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'axelar-dojo-1',
    name: 'Axelar',
    chainName: 'axelar',
    type: 'cosmos',
    enabled: false,
    symbol: 'AXL',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://axelar-rpc.pops.one:443',
      'https://axelar-rpc.qubelabs.io:443',
      'https://rpc.lavenderfive.com:443/axelar',
      'https://axelar-rpc.polkachu.com',
      'https://axelar-rpc.publicnode.com:443'
    ],
    rest: [
      'https://axelar-lcd.qubelabs.io:443',
      'https://axelar-api.polkachu.com',
      'https://axelar-rest.publicnode.com'
    ],
    bech32Prefix: 'axelar',
    feeDenom: 'uaxl',
    gasPrice: '0.007',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/axelar/images/axl.png',
    explorerUrl: 'https://www.mintscan.io/axelar',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'evmos_9001-2',
    name: 'Evmos',
    chainName: 'evmos',
    type: 'cosmos',
    enabled: false,
    symbol: 'AEVMOS',
    decimals: 6,
    coinType: 60,
    // Official Blockdaemon hops no longer resolve. PublicNode and Polkachu
    // Evmos subdomains are gone. Lavender.Five remains the public hop.
    rpc: [
      'https://rpc.lavenderfive.com:443/evmos'
    ],
    rest: [
      'https://rest.lavenderfive.com:443/evmos'
    ],
    bech32Prefix: 'evmos',
    feeDenom: 'aevmos',
    gasPrice: '25000000000',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/evmos/images/evmos.png',
    explorerUrl: 'https://www.mintscan.io/evmos',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'noble-1',
    name: 'Noble',
    chainName: 'noble',
    type: 'cosmos',
    enabled: false,
    symbol: 'NOBLE',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://noble-rpc.polkachu.com',
      'https://rpc.lavenderfive.com:443/noble',
      'https://noble-rpc.owallet.io'
    ],
    rest: [
      'https://noble-api.polkachu.com',
      'https://rest.lavenderfive.com:443/noble',
      'https://noble-rest.owallet.io'
    ],
    bech32Prefix: 'noble',
    feeDenom: 'uusdc',
    gasPrice: '0.1',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/noble/images/stake.png',
    explorerUrl: 'https://www.mintscan.io/noble',
    explorerAccountPath: '/account/{address}',
    explorerTxPath: '/txs/{txHash}'
  },
  {
    id: 'stride-1',
    name: 'Stride',
    chainName: 'stride',
    type: 'cosmos',
    enabled: false,
    symbol: 'STRD',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://stride-rpc.polkachu.com/',
      'https://rpc.lavenderfive.com:443/stride'
    ],
    rest: [
      'https://stride-api.polkachu.com/',
      'https://rest.lavenderfive.com:443/stride',
      'https://stride.api.kjnodes.com'
    ],
    bech32Prefix: 'stride',
    feeDenom: 'ustrd',
    gasPrice: '0.005',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/strd.png',
    explorerUrl: 'https://www.mintscan.io/stride',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'phoenix-1',
    name: 'Terra',
    chainName: 'terra2',
    type: 'cosmos',
    enabled: false,
    symbol: 'LUNA',
    decimals: 6,
    coinType: 330,
    rpc: [
      'https://rpc.lavenderfive.com:443/terra2',
      'https://terra-rpc.polkachu.com',
      'https://terra-rpc.stakely.io:443/',
      'https://terra-rpc.publicnode.com:443',
      'https://rpc-terra-01.stakeflow.io'
    ],
    rest: [
      'https://terra-rest.publicnode.com',
      'https://api-terra-01.stakeflow.io',
      'https://terra-phoenix-api.highstakes.ch',
      'https://terra2.tdrsys.com'
    ],
    bech32Prefix: 'terra',
    feeDenom: 'uluna',
    gasPrice: '0.015',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/terra2/images/luna.png',
    explorerUrl: 'https://www.mintscan.io/terra',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  },
  {
    id: 'beezee-1',
    name: 'BeeZee',
    chainName: 'beezee',
    type: 'cosmos',
    enabled: true,
    symbol: 'BZE',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://rpc.getbze.com',
      'https://rpc-1.getbze.com',
      'https://rpc-2.getbze.com'
    ],
    rest: [
      'https://rest.getbze.com',
      'https://rest-1.getbze.com',
      'https://rest-2.getbze.com'
    ],
    bech32Prefix: 'bze',
    feeDenom: 'ubze',
    gasPrice: '0.025',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/beezee/images/bze.png',
    explorerUrl: 'https://explorer.getbze.com/beezee',
    explorerAccountPath: '/account/{address}',
    explorerTxPath: '/tx/{txHash}'
  },
  {
    id: 'atomone-1',
    name: 'AtomOne',
    chainName: 'atomone',
    type: 'cosmos',
    enabled: true,
    symbol: 'ATONE',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://atomone-rpc.allinbits.com:443',
      'https://atomone-rpc.cogwheel.zone',
      'https://atomone.rpc.nodeshub.online:443',
      'https://rpc-atomone.nodeist.net',
      'https://rpc-atomone-1.cros-nest.com:443'
    ],
    rest: [
      'https://atomone-api.allinbits.com',
      'https://atomone-api.cogwheel.zone',
      'https://atomone.api.nodeshub.online',
      'https://api-atomone.nodeist.net'
    ],
    bech32Prefix: 'atone',
    feeDenom: 'uphoton',
    gasPrice: '0.3',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/atomone/images/atomone.png',
    explorerUrl: 'https://www.mintscan.io/atomone',
    explorerAccountPath: '/accounts/{address}',
    explorerTxPath: '/transactions/{txHash}'
  }
];

/**
 * Get chain by registry name
 */
export function getChainByName(chainName: string): CosmosRegistryConfig | undefined {
  return COSMOS_REGISTRY_CHAINS.find(c => c.chainName === chainName);
}

/**
 * Get chain by chain ID
 */
export function getChainById(chainId: string): CosmosRegistryConfig | undefined {
  return COSMOS_REGISTRY_CHAINS.find(c => c.id === chainId);
}

/**
 * Get all enabled chains
 */
export function getEnabledChains(): CosmosRegistryConfig[] {
  return COSMOS_REGISTRY_CHAINS.filter(c => c.enabled);
}
