/**
 * Cosmos Chain Registry - Auto-generated
 * 
 * This file is generated by scripts/sync-chain-registry.ts
 * Source: https://github.com/cosmos/chain-registry
 * 
 * DO NOT EDIT MANUALLY - Run `npm run sync:chains` to update
 * 
 * Generated: 2026-01-29T16:25:45.290Z
 */

import { CosmosNetworkConfig } from './types';

/**
 * Extended config with chain registry name for dynamic fetching
 */
export interface CosmosRegistryConfig extends CosmosNetworkConfig {
  chainName: string;  // Registry name (e.g., 'osmosis', 'cosmoshub')
  logoUrl?: string;
}

/**
 * Pre-bundled Cosmos chains from the chain registry
 */
export const COSMOS_REGISTRY_CHAINS: CosmosRegistryConfig[] = [
  {
    id: 'beezee-1',
    name: 'BeeZee',
    chainName: 'beezee',
    type: 'cosmos',
    enabled: true,
    symbol: 'BZE',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://rpc.getbze.com',
      'https://rpc-1.getbze.com',
      'https://rpc-2.getbze.com',
      'https://beezee_mainnet_rpc.chain.whenmoonwhenlambo.money'
    ],
    rest: [
      'https://rest.getbze.com',
      'https://rest-1.getbze.com',
      'https://rest-2.getbze.com',
      'https://beezee_mainnet_api.chain.whenmoonwhenlambo.money'
    ],
    bech32Prefix: 'bze',
    feeDenom: 'ubze',
    gasPrice: '0.025',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/beezee/images/bze.png',
    explorerUrl: 'https://ping.pub/beezee',
    explorerAccountPath: 'https://ping.pub/beezee/account/{address}',
    explorerTxPath: 'https://ping.pub/beezee/tx/{txHash}'
  },
  {
    id: 'osmosis-1',
    name: 'Osmosis',
    chainName: 'osmosis',
    type: 'cosmos',
    enabled: true,
    symbol: 'OSMO',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://rpc.osmosis.zone/',
      'https://rpc.lavenderfive.com:443/osmosis',
      'https://rpc-osmosis.ecostake.com',
      'https://osmosis-rpc.polkachu.com',
      'https://osmosis.rpc.stakin-nodes.com'
    ],
    rest: [
      'https://lcd.osmosis.zone/',
      'https://rest.osmosis.goldenratiostaking.net',
      'https://rest.lavenderfive.com:443/osmosis',
      'https://rest-osmosis.ecostake.com',
      'https://osmosis-api.polkachu.com'
    ],
    bech32Prefix: 'osmo',
    feeDenom: 'uosmo',
    gasPrice: '0.1',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/osmosis/images/osmo.png',
    explorerUrl: 'https://www.mintscan.io/osmosis',
    explorerAccountPath: 'https://www.mintscan.io/osmosis/accounts/{address}',
    explorerTxPath: 'https://www.mintscan.io/osmosis/transactions/{txHash}'
  },
  {
    id: 'cosmoshub-4',
    name: 'Cosmos Hub',
    chainName: 'cosmoshub',
    type: 'cosmos',
    enabled: true,
    symbol: 'ATOM',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://rpc.cosmoshub-main.ccvalidators.com:443',
      'https://cosmoshub.tendermintrpc.lava.build:443',
      'https://cosmos-rpc.quickapi.com:443',
      'https://cosmos-rpc.onivalidator.com',
      'https://rpc-cosmoshub.whispernode.com:443'
    ],
    rest: [
      'https://rest.cosmoshub-main.ccvalidators.com:443',
      'https://cosmoshub.lava.build:443',
      'https://cosmos-lcd.quickapi.com:443',
      'https://rest.cosmoshub.goldenratiostaking.net',
      'https://rest.lavenderfive.com:443/cosmoshub'
    ],
    bech32Prefix: 'cosmos',
    feeDenom: 'uatom',
    gasPrice: '0.025',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/cosmoshub/images/atom.png',
    explorerUrl: 'https://www.mintscan.io/cosmos',
    explorerAccountPath: 'https://www.mintscan.io/cosmos/accounts/{address}',
    explorerTxPath: 'https://www.mintscan.io/cosmos/transactions/{txHash}'
  },
  {
    id: 'atomone-1',
    name: 'AtomOne',
    chainName: 'atomone',
    type: 'cosmos',
    enabled: true,
    symbol: 'ATONE',
    decimals: 6,
    coinType: 118,
    rpc: [
      'https://atomone-rpc.allinbits.com:443',
      'https://atomone-rpc.cogwheel.zone',
      'https://atomone.rpc.nodeshub.online:443',
      'https://rpc-atomone.nodeist.net',
      'https://rpc-atomone-1.cros-nest.com:443'
    ],
    rest: [
      'https://atomone-api.allinbits.com',
      'https://atomone-api.cogwheel.zone',
      'https://atomone.api.nodeshub.online',
      'https://api-atomone.nodeist.net',
      'https://rest-atomone-1.cros-nest.com:443'
    ],
    bech32Prefix: 'atone',
    feeDenom: 'uphoton',
    gasPrice: '0.3',
    features: [
      'stargate',
      'ibc-transfer',
      'no-legacy-stdTx'
    ],
    logoUrl: 'https://raw.githubusercontent.com/cosmos/chain-registry/master/atomone/images/atomone.png',
    explorerUrl: 'https://explorer.allinbits.com/atomone',
    explorerAccountPath: 'https://explorer.allinbits.com/atomone/account/{address}',
    explorerTxPath: 'https://explorer.allinbits.com/atomone/tx/{txHash}'
  }
];

/**
 * Get chain by registry name
 */
export function getChainByName(chainName: string): CosmosRegistryConfig | undefined {
  return COSMOS_REGISTRY_CHAINS.find(c => c.chainName === chainName);
}

/**
 * Get chain by chain ID
 */
export function getChainById(chainId: string): CosmosRegistryConfig | undefined {
  return COSMOS_REGISTRY_CHAINS.find(c => c.id === chainId);
}

/**
 * Get all enabled chains
 */
export function getEnabledChains(): CosmosRegistryConfig[] {
  return COSMOS_REGISTRY_CHAINS.filter(c => c.enabled);
}
