/**
 * EVM Chain Registry - Auto-generated
 *
 * This file is generated by scripts/sync-evm-registry.ts
 * Source: https://github.com/ethereum-lists/chains
 *
 * DO NOT EDIT MANUALLY - Run `npm run sync:evm` to update
 *
 * Generated: 2026-01-29T16:53:55.293Z
 */

import { EvmNetworkConfig } from './types';

/**
 * Extended config with registry metadata
 */
export interface EvmRegistryConfig extends EvmNetworkConfig {
  shortName: string; // Registry short name for lookups
  infoUrl?: string; // Chain info URL
  isTestnet?: boolean; // Whether this is a testnet
}

/**
 * Pre-bundled EVM chains from the chain registry
 */
export const EVM_REGISTRY_CHAINS: EvmRegistryConfig[] = [
  {
    id: 'eth-mainnet',
    name: 'Ethereum Mainnet',
    shortName: 'eth',
    type: 'evm',
    enabled: true,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 1,
    rpcUrls: [
      'https://api.mycryptoapi.com/eth',
      'https://cloudflare-eth.com',
      'https://ethereum-rpc.publicnode.com',
      'https://mainnet.gateway.tenderly.co',
      'https://rpc.blocknative.com/boost'
    ],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://etherscan.io',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://ethereum.org',
    isTestnet: false
  },
  {
    id: 'oeth-mainnet',
    name: 'OP Mainnet',
    shortName: 'oeth',
    type: 'evm',
    enabled: true,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 10,
    rpcUrls: [
      'https://mainnet.optimism.io',
      'https://optimism-rpc.publicnode.com',
      'https://optimism.gateway.tenderly.co',
      'https://optimism.drpc.org'
    ],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://optimistic.etherscan.io',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://optimism.io',
    isTestnet: false
  },
  {
    id: 'bnb-mainnet',
    name: 'BNB Smart Chain Mainnet',
    shortName: 'bnb',
    type: 'evm',
    enabled: true,
    symbol: 'BNB',
    decimals: 18,
    coinType: 714,
    chainId: 56,
    rpcUrls: [
      'https://bsc-dataseed1.bnbchain.org',
      'https://bsc-dataseed2.bnbchain.org',
      'https://bsc-dataseed3.bnbchain.org',
      'https://bsc-dataseed4.bnbchain.org',
      'https://bsc-dataseed1.defibit.io'
    ],
    nativeCurrency: {
      name: 'BNB Chain Native Token',
      symbol: 'BNB',
      decimals: 18
    },
    explorerUrl: 'https://bscscan.com',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://www.bnbchain.org/en',
    isTestnet: false
  },
  {
    id: 'pol-mainnet',
    name: 'Polygon Mainnet',
    shortName: 'pol',
    type: 'evm',
    enabled: true,
    symbol: 'POL',
    decimals: 18,
    coinType: 966,
    chainId: 137,
    rpcUrls: [
      'https://polygon-rpc.com/',
      'https://rpc-mainnet.matic.network',
      'https://matic-mainnet.chainstacklabs.com',
      'https://rpc-mainnet.maticvigil.com',
      'https://rpc-mainnet.matic.quiknode.pro'
    ],
    nativeCurrency: {
      name: 'POL',
      symbol: 'POL',
      decimals: 18
    },
    explorerUrl: 'https://polygonscan.com',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://polygon.technology/',
    isTestnet: false
  },
  {
    id: 'base-mainnet',
    name: 'Base',
    shortName: 'base',
    type: 'evm',
    enabled: true,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 8453,
    rpcUrls: [
      'https://mainnet.base.org/',
      'https://developer-access-mainnet.base.org/',
      'https://base.gateway.tenderly.co',
      'https://base-rpc.publicnode.com'
    ],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://basescan.org',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://base.org',
    isTestnet: false
  },
  {
    id: 'arb1-mainnet',
    name: 'Arbitrum One',
    shortName: 'arb1',
    type: 'evm',
    enabled: true,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 42161,
    rpcUrls: [
      'https://arb1.arbitrum.io/rpc',
      'https://arbitrum-one-rpc.publicnode.com'
    ],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://arbiscan.io',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://arbitrum.io',
    isTestnet: false
  },
  {
    id: 'cro-mainnet',
    name: 'Cronos Mainnet',
    shortName: 'cro',
    type: 'evm',
    enabled: false,
    symbol: 'CRO',
    decimals: 18,
    coinType: 60,
    chainId: 25,
    rpcUrls: [
      'https://evm.cronos.org',
      'https://cronos-evm-rpc.publicnode.com',
      'https://cronos.drpc.org'
    ],
    nativeCurrency: {
      name: 'Cronos',
      symbol: 'CRO',
      decimals: 18
    },
    explorerUrl: 'https://explorer.cronos.org',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://cronos.org/',
    isTestnet: false
  },
  {
    id: 'gno-mainnet',
    name: 'Gnosis',
    shortName: 'gno',
    type: 'evm',
    enabled: false,
    symbol: 'XDAI',
    decimals: 18,
    coinType: 700,
    chainId: 100,
    rpcUrls: [
      'https://rpc.gnosischain.com',
      'https://rpc.gnosis.gateway.fm',
      'https://rpc.ankr.com/gnosis',
      'https://gnosischain-rpc.gateway.pokt.network',
      'https://gnosis-mainnet.public.blastapi.io'
    ],
    nativeCurrency: {
      name: 'xDAI',
      symbol: 'XDAI',
      decimals: 18
    },
    explorerUrl: 'https://gnosisscan.io',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://docs.gnosischain.com',
    isTestnet: false
  },
  {
    id: 'manta-mainnet',
    name: 'Manta Pacific Mainnet',
    shortName: 'manta',
    type: 'evm',
    enabled: false,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 169,
    rpcUrls: [
      'https://pacific-rpc.manta.network/http',
      'https://manta-pacific.drpc.org'
    ],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://pacific-explorer.manta.network',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://pacific-info.manta.network',
    isTestnet: false
  },
  {
    id: 'ftm-mainnet',
    name: 'Fantom Opera',
    shortName: 'ftm',
    type: 'evm',
    enabled: false,
    symbol: 'FTM',
    decimals: 18,
    coinType: 60,
    chainId: 250,
    rpcUrls: [
      'https://rpc.ftm.tools',
      'https://fantom-rpc.publicnode.com',
      'https://fantom.drpc.org'
    ],
    nativeCurrency: {
      name: 'Fantom',
      symbol: 'FTM',
      decimals: 18
    },
    explorerUrl: 'https://ftmscan.com',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://fantom.foundation',
    isTestnet: false
  },
  {
    id: 'zksync-mainnet',
    name: 'zkSync Mainnet',
    shortName: 'zksync',
    type: 'evm',
    enabled: false,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 324,
    rpcUrls: [
      'https://mainnet.era.zksync.io',
      'https://zksync.drpc.org'
    ],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://explorer.zksync.io',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://zksync.io/',
    isTestnet: false
  },
  {
    id: 'metis-andromeda-mainnet',
    name: 'Metis Andromeda Mainnet',
    shortName: 'metis-andromeda',
    type: 'evm',
    enabled: false,
    symbol: 'METIS',
    decimals: 18,
    coinType: 60,
    chainId: 1088,
    rpcUrls: [
      'https://andromeda.metis.io/?owner=1088',
      'https://metis.drpc.org',
      'https://metis-rpc.publicnode.com'
    ],
    nativeCurrency: {
      name: 'Metis',
      symbol: 'METIS',
      decimals: 18
    },
    explorerUrl: 'https://andromeda-explorer.metis.io',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://www.metis.io',
    isTestnet: false
  },
  {
    id: 'zkevm-mainnet',
    name: 'Polygon zkEVM',
    shortName: 'zkevm',
    type: 'evm',
    enabled: false,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 1101,
    rpcUrls: [
      'https://zkevm-rpc.com',
      'https://polygon-zkevm.drpc.org'
    ],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://zkevm.polygonscan.com',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://polygon.technology/polygon-zkevm',
    isTestnet: false
  },
  {
    id: 'mbeam-mainnet',
    name: 'Moonbeam',
    shortName: 'mbeam',
    type: 'evm',
    enabled: false,
    symbol: 'GLMR',
    decimals: 18,
    coinType: 60,
    chainId: 1284,
    rpcUrls: [
      'https://rpc.api.moonbeam.network',
      'https://moonbeam.public.blastapi.io',
      'https://moonbeam-rpc.dwellir.com',
      'https://moonbeam.api.onfinality.io/public',
      'https://moonbeam.unitedbloc.com'
    ],
    nativeCurrency: {
      name: 'Glimmer',
      symbol: 'GLMR',
      decimals: 18
    },
    explorerUrl: 'https://moonbeam.moonscan.io',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://moonbeam.network/networks/moonbeam/',
    isTestnet: false
  },
  {
    id: 'mriver-mainnet',
    name: 'Moonriver',
    shortName: 'mriver',
    type: 'evm',
    enabled: false,
    symbol: 'MOVR',
    decimals: 18,
    coinType: 60,
    chainId: 1285,
    rpcUrls: [
      'https://rpc.api.moonriver.moonbeam.network',
      'https://moonriver.public.blastapi.io',
      'https://moonriver-rpc.dwellir.com',
      'https://moonriver.api.onfinality.io/public',
      'https://moonriver.unitedbloc.com'
    ],
    nativeCurrency: {
      name: 'Moonriver',
      symbol: 'MOVR',
      decimals: 18
    },
    explorerUrl: 'https://moonriver.moonscan.io',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://moonbeam.network/networks/moonriver/',
    isTestnet: false
  },
  {
    id: 'mantle-mainnet',
    name: 'Mantle',
    shortName: 'mantle',
    type: 'evm',
    enabled: false,
    symbol: 'MNT',
    decimals: 18,
    coinType: 60,
    chainId: 5000,
    rpcUrls: [
      'https://rpc.mantle.xyz',
      'https://mantle-rpc.publicnode.com'
    ],
    nativeCurrency: {
      name: 'Mantle',
      symbol: 'MNT',
      decimals: 18
    },
    explorerUrl: 'https://mantlescan.xyz',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://mantle.xyz',
    isTestnet: false
  },
  {
    id: 'mode-mainnet',
    name: 'Mode',
    shortName: 'mode',
    type: 'evm',
    enabled: false,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 34443,
    rpcUrls: [
      'https://mainnet.mode.network',
      'https://mode.drpc.org'
    ],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://explorer.mode.network',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://docs.mode.network/',
    isTestnet: false
  },
  {
    id: 'celo-mainnet',
    name: 'Celo Mainnet',
    shortName: 'celo',
    type: 'evm',
    enabled: false,
    symbol: 'CELO',
    decimals: 18,
    coinType: 60,
    chainId: 42220,
    rpcUrls: [
      'https://forno.celo.org'
    ],
    nativeCurrency: {
      name: 'CELO',
      symbol: 'CELO',
      decimals: 18
    },
    explorerUrl: 'https://celoscan.io',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://docs.celo.org/',
    isTestnet: false
  },
  {
    id: 'avax-mainnet',
    name: 'Avalanche C-Chain',
    shortName: 'avax',
    type: 'evm',
    enabled: false,
    symbol: 'AVAX',
    decimals: 18,
    coinType: 9005,
    chainId: 43114,
    rpcUrls: [
      'https://api.avax.network/ext/bc/C/rpc',
      'https://avalanche-c-chain-rpc.publicnode.com'
    ],
    nativeCurrency: {
      name: 'Avalanche',
      symbol: 'AVAX',
      decimals: 18
    },
    explorerUrl: 'https://snowscan.xyz',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://www.avax.network/',
    isTestnet: false
  },
  {
    id: 'linea-mainnet',
    name: 'Linea',
    shortName: 'linea',
    type: 'evm',
    enabled: false,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 59144,
    rpcUrls: [
      'https://rpc.linea.build',
      'https://linea-rpc.publicnode.com'
    ],
    nativeCurrency: {
      name: 'Linea Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://lineascan.build',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://linea.build',
    isTestnet: false
  },
  {
    id: 'blastmainnet-mainnet',
    name: 'Blast',
    shortName: 'blastmainnet',
    type: 'evm',
    enabled: false,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 81457,
    rpcUrls: [
      'https://rpc.blast.io',
      'https://rpc.ankr.com/blast',
      'https://blast.din.dev/rpc',
      'https://blastl2-mainnet.public.blastapi.io',
      'https://blast.blockpi.network/v1/rpc/public'
    ],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://blastscan.io',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://blast.io/',
    isTestnet: false
  },
  {
    id: 'scr-mainnet',
    name: 'Scroll',
    shortName: 'scr',
    type: 'evm',
    enabled: false,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 534352,
    rpcUrls: [
      'https://rpc.scroll.io',
      'https://rpc.ankr.com/scroll',
      'https://scroll-mainnet.chainstacklabs.com',
      'https://scroll-rpc.publicnode.com'
    ],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://scrollscan.com',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://scroll.io',
    isTestnet: false
  },
  {
    id: 'zora-mainnet',
    name: 'Zora',
    shortName: 'zora',
    type: 'evm',
    enabled: false,
    symbol: 'ETH',
    decimals: 18,
    coinType: 60,
    chainId: 7777777,
    rpcUrls: [
      'https://rpc.zora.energy/'
    ],
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://explorer.zora.energy',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://zora.energy',
    isTestnet: false
  },
  {
    id: 'basesep-testnet',
    name: 'Base Sepolia Testnet',
    shortName: 'basesep',
    type: 'evm',
    enabled: false,
    symbol: 'ETH',
    decimals: 18,
    coinType: 1,
    chainId: 84532,
    rpcUrls: [
      'https://sepolia.base.org',
      'https://base-sepolia-rpc.publicnode.com'
    ],
    nativeCurrency: {
      name: 'Sepolia Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://sepolia.basescan.org',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://base.org',
    isTestnet: true
  },
  {
    id: 'sep-testnet',
    name: 'Ethereum Sepolia',
    shortName: 'sep',
    type: 'evm',
    enabled: false,
    symbol: 'ETH',
    decimals: 18,
    coinType: 1,
    chainId: 11155111,
    rpcUrls: [
      'https://rpc.sepolia.org',
      'https://rpc2.sepolia.org',
      'https://rpc.sepolia.ethpandaops.io',
      'https://sepolia.gateway.tenderly.co',
      'https://ethereum-sepolia-rpc.publicnode.com'
    ],
    nativeCurrency: {
      name: 'Sepolia Ether',
      symbol: 'ETH',
      decimals: 18
    },
    explorerUrl: 'https://sepolia.etherscan.io',
    explorerAccountPath: '/address/{address}',
    explorerTxPath: '/tx/{txHash}',
    infoUrl: 'https://sepolia.otterscan.io',
    isTestnet: true
  }
];

/**
 * Get chain by chain ID
 */
export function getEvmChainById(chainId: number): EvmRegistryConfig | undefined {
  return EVM_REGISTRY_CHAINS.find((c) => c.chainId === chainId);
}

/**
 * Get chain by short name
 */
export function getEvmChainByShortName(shortName: string): EvmRegistryConfig | undefined {
  return EVM_REGISTRY_CHAINS.find(
    (c) => c.shortName.toLowerCase() === shortName.toLowerCase()
  );
}

/**
 * Get chain by internal ID
 */
export function getEvmChainByInternalId(id: string): EvmRegistryConfig | undefined {
  return EVM_REGISTRY_CHAINS.find((c) => c.id === id);
}

/**
 * Get all enabled chains
 */
export function getEnabledEvmChains(): EvmRegistryConfig[] {
  return EVM_REGISTRY_CHAINS.filter((c) => c.enabled);
}

/**
 * Get all mainnet chains
 */
export function getMainnetEvmChains(): EvmRegistryConfig[] {
  return EVM_REGISTRY_CHAINS.filter((c) => !c.isTestnet);
}

/**
 * Get all testnet chains
 */
export function getTestnetEvmChains(): EvmRegistryConfig[] {
  return EVM_REGISTRY_CHAINS.filter((c) => c.isTestnet);
}
