import fs from 'fs';
import path from 'path';

const registryPath = path.resolve(__dirname, '..', 'src/lib/assets/chainRegistry.ts');

export function syncChainRegistry(data: unknown): void {
  const contents = `// Auto-generated by scripts/sync-chain-registry.ts\nexport const chainRegistry = ${JSON.stringify(data, null, 2)} as const;\n`;
  fs.writeFileSync(registryPath, contents);
}

if (require.main === module) {
  syncChainRegistry([]);
}
