import fs from 'fs';
import path from 'path';

const REGISTRY_URL = 'https://registry.vidulum.network/chains.json';
const OUT = path.resolve(__dirname, '..', 'src', 'lib', 'assets', 'chainRegistry.ts');

async function main() {
  const res = await fetch(REGISTRY_URL);
  if (!res.ok) throw new Error(`Registry fetch failed: ${res.status}`);
  const data = await res.json();
  const contents = `// AUTO-GENERATED by scripts/sync-chain-registry.ts — do not edit by hand.\nexport const chainRegistry = ${JSON.stringify(data, null, 2)} as const;\n`;
  fs.writeFileSync(OUT, contents);
  console.log('chainRegistry.ts updated');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
