import fs from 'fs';
import path from 'path';

// Syncs the cosmos chain registry snapshot into src/lib/assets/chainRegistry.ts.
// This script only handles public chain metadata; it never touches keys or funds.

const OUT = path.resolve(__dirname, '../src/lib/assets/chainRegistry.ts');

export function generateRegistry(entries: { chainId: string; name: string }[]): string {
  const body = entries
    .map((e) => `  { chainId: '${e.chainId}', name: '${e.name}' },`)
    .join('\n');
  return `// AUTO-GENERATED by scripts/sync-chain-registry.ts. Do not edit by hand.\nexport interface ChainEntry {\n  chainId: string;\n  name: string;\n}\n\nexport const chainRegistry: ChainEntry[] = [\n${body}\n];\n`;
}

if (require.main === module) {
  const entries = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../data/chains.json'), 'utf8'));
  fs.writeFileSync(OUT, generateRegistry(entries));
  console.log('Wrote', OUT);
}
