import fs from 'node:fs';
import path from 'node:path';

const OUT = path.resolve(__dirname, '..', 'src', 'lib', 'assets', 'evmRegistry.ts');

export function generateEvmRegistry(chains: { chainId: number; name: string }[]): string {
  const body = chains
    .map((c) => `  { chainId: ${c.chainId}, name: '${c.name}' },`)
    .join('\n');
  return `// AUTO-GENERATED by scripts/sync-evm-registry.ts — do not edit by hand.
export const EVM_REGISTRY = [
${body}
] as const;
`;
}

if (require.main === module) {
  const chains = JSON.parse(
    fs.readFileSync(path.resolve(__dirname, 'evm-registry.json'), 'utf8'),
  );
  fs.writeFileSync(OUT, generateEvmRegistry(chains));
  console.log('Wrote EVM registry');
}
