import fs from 'fs';
import path from 'path';

// Syncs EVM chain metadata (public info only) into the app assets.
const OUT = path.resolve(__dirname, '../src/lib/assets/evmRegistry.ts');

export function generateEvmRegistry(entries: { chainId: number; name: string }[]): string {
  const body = entries.map((e) => `  { chainId: ${e.chainId}, name: '${e.name}' },`).join('\n');
  return `// AUTO-GENERATED by scripts/sync-evm-registry.ts. Do not edit by hand.\nexport interface EvmEntry {\n  chainId: number;\n  name: string;\n}\n\nexport const evmRegistry = [\n${body}\n];\n`;
}

if (require.main === module) {
  const entries = JSON.parse(fs.readFileSync(path.resolve(__dirname, '../data/evm.json'), 'utf8'));
  fs.writeFileSync(OUT, generateEvmRegistry(entries));
  console.log('Wrote', OUT);
}
