// AUTO-GENERATED by scripts/sync-chain-registry.ts — do not edit by hand.
export const chainRegistry = {
  vidulum: {
    name: 'Vidulum Mainnet',
    chainId: 'vidulum-1',
    bech32Prefix: 'vdl',
    rpc: 'https://rpc.vidulum.network',
    rest: 'https://api.vidulum.network',
    denom: 'uvdl',
    displayDenom: 'VDL',
    decimals: 6,
  },
} as const;
