// AUTO-GENERATED by scripts/sync-chain-registry.ts — do not edit by hand.

export type NetworkType = 'cosmos' | 'evm' | 'svm' | 'utxo';

export interface ChainEntry {
  id: string;
  name: string;
  networkType: NetworkType;
  chainId?: number;
  bech32Prefix?: string;
  denom: string;
  decimals: number;
}

export const CHAIN_REGISTRY: readonly ChainEntry[] = [
  { id: 'vidulum', name: 'Vidulum', networkType: 'cosmos', bech32Prefix: 'vdl', denom: 'uvdl', decimals: 6 },
  { id: 'cosmoshub', name: 'Cosmos Hub', networkType: 'cosmos', bech32Prefix: 'cosmos', denom: 'uatom', decimals: 6 },
  { id: 'osmosis', name: 'Osmosis', networkType: 'cosmos', bech32Prefix: 'osmo', denom: 'uosmo', decimals: 6 },
  { id: 'ethereum', name: 'Ethereum', networkType: 'evm', chainId: 1, denom: 'eth', decimals: 18 },
  { id: 'polygon', name: 'Polygon', networkType: 'evm', chainId: 137, denom: 'pol', decimals: 18 },
  { id: 'solana', name: 'Solana', networkType: 'svm', denom: 'sol', decimals: 9 },
  { id: 'bitcoin', name: 'Bitcoin', networkType: 'utxo', denom: 'btc', decimals: 8 },
] as const;

export function getChain(id: string): ChainEntry | undefined {
  return CHAIN_REGISTRY.find((c) => c.id === id);
}
