/**
 * Cosmos IBC Channel Registry - Auto-generated
 * 
 * This file is generated by scripts/sync-chain-registry.ts
 * Source: https://github.com/cosmos/chain-registry/_IBC
 * 
 * DO NOT EDIT MANUALLY - Run `npm run sync:chains` to update
 * 
 * Generated: 2026-02-03T14:31:35.010Z
 */

/**
 * IBC Channel info for cross-chain transfers
 */
export interface IBCChannelConfig {
  sourceChainId: string;
  sourceChainName: string;
  sourceChannelId: string;
  sourcePort: string;
  destChainId: string;
  destChainName: string;
  destChannelId: string;
  destPort: string;
  status: 'ACTIVE' | 'INACTIVE' | 'UNKNOWN';
}

/**
 * Pre-bundled IBC channels between enabled chains
 */
export const IBC_CHANNELS: IBCChannelConfig[] = [
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-141',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-0',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-0',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-141',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-220',
    sourcePort: 'transfer',
    destChainId: 'injective-1',
    destChainName: 'injective',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'injective-1',
    sourceChainName: 'injective',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-220',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-584',
    sourcePort: 'transfer',
    destChainId: 'pacific-1',
    destChainName: 'sei',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'pacific-1',
    sourceChainName: 'sei',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-584',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-730',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-239',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-239',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-730',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-207',
    sourcePort: 'transfer',
    destChainId: 'juno-1',
    destChainName: 'juno',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'juno-1',
    sourceChainName: 'juno',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-207',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'akashnet-2',
    sourceChainName: 'akash',
    sourceChannelId: 'channel-17',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-184',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-184',
    sourcePort: 'transfer',
    destChainId: 'akashnet-2',
    destChainName: 'akash',
    destChannelId: 'channel-17',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-343',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-0',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-0',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-343',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-569',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-569',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'archway-1',
    sourceChainName: 'archway',
    sourceChannelId: 'channel-0',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-623',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-623',
    sourcePort: 'transfer',
    destChainId: 'archway-1',
    destChainName: 'archway',
    destChannelId: 'channel-0',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-2',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-293',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-293',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-2',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-292',
    sourcePort: 'transfer',
    destChainId: 'evmos_9001-2',
    destChainName: 'evmos',
    destChannelId: 'channel-3',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'evmos_9001-2',
    sourceChainName: 'evmos',
    sourceChannelId: 'channel-3',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-292',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-536',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-4',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-4',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-536',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-391',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-0',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-0',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-391',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'cosmoshub-4',
    sourceChainName: 'cosmoshub',
    sourceChannelId: 'channel-339',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-0',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-0',
    sourcePort: 'transfer',
    destChainId: 'cosmoshub-4',
    destChainName: 'cosmoshub',
    destChannelId: 'channel-339',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'celestia',
    sourceChainName: 'celestia',
    sourceChannelId: 'channel-2',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-6994',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-6994',
    sourcePort: 'transfer',
    destChainId: 'celestia',
    destChainName: 'celestia',
    destChannelId: 'channel-2',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'dydx-mainnet-1',
    sourceChainName: 'dydx',
    sourceChannelId: 'channel-3',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-6787',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-6787',
    sourcePort: 'transfer',
    destChainId: 'dydx-mainnet-1',
    destChainName: 'dydx',
    destChannelId: 'channel-3',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'injective-1',
    sourceChainName: 'injective',
    sourceChannelId: 'channel-8',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-122',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-122',
    sourcePort: 'transfer',
    destChainId: 'injective-1',
    destChainName: 'injective',
    destChannelId: 'channel-8',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-782',
    sourcePort: 'transfer',
    destChainId: 'pacific-1',
    destChainName: 'sei',
    destChannelId: 'channel-0',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'pacific-1',
    sourceChainName: 'sei',
    sourceChannelId: 'channel-0',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-782',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-75',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-0',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-0',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-75',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'juno-1',
    sourceChainName: 'juno',
    sourceChannelId: 'channel-0',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-42',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-42',
    sourcePort: 'transfer',
    destChainId: 'juno-1',
    destChainName: 'juno',
    destChannelId: 'channel-0',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'akashnet-2',
    sourceChainName: 'akash',
    sourceChannelId: 'channel-9',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'akashnet-2',
    destChainName: 'akash',
    destChannelId: 'channel-9',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-3',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-259',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-259',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-3',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-10',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-874',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-874',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-10',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'archway-1',
    sourceChainName: 'archway',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-1429',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-1429',
    sourcePort: 'transfer',
    destChainId: 'archway-1',
    destChainName: 'archway',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-3',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-208',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-208',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-3',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'evmos_9001-2',
    sourceChainName: 'evmos',
    sourceChannelId: 'channel-0',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-204',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-204',
    sourcePort: 'transfer',
    destChainId: 'evmos_9001-2',
    destChainName: 'evmos',
    destChannelId: 'channel-0',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-750',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-750',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-326',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-5',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-5',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-326',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-251',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-251',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'beezee-1',
    sourceChainName: 'beezee',
    sourceChannelId: 'channel-0',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-340',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-340',
    sourcePort: 'transfer',
    destChainId: 'beezee-1',
    destChainName: 'beezee',
    destChannelId: 'channel-0',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'atomone-1',
    sourceChainName: 'atomone',
    sourceChannelId: 'channel-2',
    sourcePort: 'transfer',
    destChainId: 'osmosis-1',
    destChainName: 'osmosis',
    destChannelId: 'channel-94814',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'osmosis-1',
    sourceChainName: 'osmosis',
    sourceChannelId: 'channel-94814',
    sourcePort: 'transfer',
    destChainId: 'atomone-1',
    destChainName: 'atomone',
    destChannelId: 'channel-2',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'celestia',
    sourceChainName: 'celestia',
    sourceChannelId: 'channel-7',
    sourcePort: 'transfer',
    destChainId: 'injective-1',
    destChainName: 'injective',
    destChannelId: 'channel-152',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'injective-1',
    sourceChainName: 'injective',
    sourceChannelId: 'channel-152',
    sourcePort: 'transfer',
    destChainId: 'celestia',
    destChainName: 'celestia',
    destChannelId: 'channel-7',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'celestia',
    sourceChainName: 'celestia',
    sourceChannelId: 'channel-33',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-291',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-291',
    sourcePort: 'transfer',
    destChainId: 'celestia',
    destChainName: 'celestia',
    destChannelId: 'channel-33',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'celestia',
    sourceChainName: 'celestia',
    sourceChannelId: 'channel-8',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-35',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-35',
    sourcePort: 'transfer',
    destChainId: 'celestia',
    destChainName: 'celestia',
    destChannelId: 'channel-8',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-125',
    sourcePort: 'transfer',
    destChainId: 'celestia',
    destChainName: 'celestia',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'celestia',
    sourceChainName: 'celestia',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-125',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'celestia',
    sourceChainName: 'celestia',
    sourceChannelId: 'channel-26',
    sourcePort: 'transfer',
    destChainId: 'evmos_9001-2',
    destChainName: 'evmos',
    destChannelId: 'channel-106',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'evmos_9001-2',
    sourceChainName: 'evmos',
    sourceChannelId: 'channel-106',
    sourcePort: 'transfer',
    destChainId: 'celestia',
    destChainName: 'celestia',
    destChannelId: 'channel-26',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'celestia',
    sourceChainName: 'celestia',
    sourceChannelId: 'channel-4',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-162',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-162',
    sourcePort: 'transfer',
    destChainId: 'celestia',
    destChainName: 'celestia',
    destChannelId: 'channel-4',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'celestia',
    sourceChainName: 'celestia',
    sourceChannelId: 'channel-15',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-300',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-300',
    sourcePort: 'transfer',
    destChainId: 'celestia',
    destChainName: 'celestia',
    destChannelId: 'channel-15',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'dydx-mainnet-1',
    sourceChainName: 'dydx',
    sourceChannelId: 'channel-5',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-118',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-118',
    sourcePort: 'transfer',
    destChainId: 'dydx-mainnet-1',
    destChainName: 'dydx',
    destChannelId: 'channel-5',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'dydx-mainnet-1',
    sourceChainName: 'dydx',
    sourceChannelId: 'channel-11',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-48',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-48',
    sourcePort: 'transfer',
    destChainId: 'dydx-mainnet-1',
    destChainName: 'dydx',
    destChannelId: 'channel-11',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'dydx-mainnet-1',
    sourceChainName: 'dydx',
    sourceChannelId: 'channel-23',
    sourcePort: 'transfer',
    destChainId: 'evmos_9001-2',
    destChainName: 'evmos',
    destChannelId: 'channel-107',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'evmos_9001-2',
    sourceChainName: 'evmos',
    sourceChannelId: 'channel-107',
    sourcePort: 'transfer',
    destChainId: 'dydx-mainnet-1',
    destChainName: 'dydx',
    destChannelId: 'channel-23',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'dydx-mainnet-1',
    sourceChainName: 'dydx',
    sourceChannelId: 'channel-0',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-33',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-33',
    sourcePort: 'transfer',
    destChainId: 'dydx-mainnet-1',
    destChainName: 'dydx',
    destChannelId: 'channel-0',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'dydx-mainnet-1',
    sourceChainName: 'dydx',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-160',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-160',
    sourcePort: 'transfer',
    destChainId: 'dydx-mainnet-1',
    destChainName: 'dydx',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'dydx-mainnet-1',
    sourceChainName: 'dydx',
    sourceChannelId: 'channel-9',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-299',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-299',
    sourcePort: 'transfer',
    destChainId: 'dydx-mainnet-1',
    destChainName: 'dydx',
    destChannelId: 'channel-9',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'injective-1',
    sourceChainName: 'injective',
    sourceChannelId: 'channel-98',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-54',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-54',
    sourcePort: 'transfer',
    destChainId: 'injective-1',
    destChainName: 'injective',
    destChannelId: 'channel-98',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'injective-1',
    sourceChainName: 'injective',
    sourceChannelId: 'channel-177',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-60',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-60',
    sourcePort: 'transfer',
    destChainId: 'injective-1',
    destChainName: 'injective',
    destChannelId: 'channel-177',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-10',
    sourcePort: 'transfer',
    destChainId: 'injective-1',
    destChainName: 'injective',
    destChannelId: 'channel-84',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'injective-1',
    sourceChainName: 'injective',
    sourceChannelId: 'channel-84',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-10',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'evmos_9001-2',
    sourceChainName: 'evmos',
    sourceChannelId: 'channel-10',
    sourcePort: 'transfer',
    destChainId: 'injective-1',
    destChainName: 'injective',
    destChannelId: 'channel-83',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'injective-1',
    sourceChainName: 'injective',
    sourceChannelId: 'channel-83',
    sourcePort: 'transfer',
    destChainId: 'evmos_9001-2',
    destChainName: 'evmos',
    destChannelId: 'channel-10',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'injective-1',
    sourceChainName: 'injective',
    sourceChannelId: 'channel-148',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-31',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-31',
    sourcePort: 'transfer',
    destChainId: 'injective-1',
    destChainName: 'injective',
    destChannelId: 'channel-148',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'injective-1',
    sourceChainName: 'injective',
    sourceChannelId: 'channel-89',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-6',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-6',
    sourcePort: 'transfer',
    destChainId: 'injective-1',
    destChainName: 'injective',
    destChannelId: 'channel-89',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'injective-1',
    sourceChainName: 'injective',
    sourceChannelId: 'channel-151',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-255',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-255',
    sourcePort: 'transfer',
    destChainId: 'injective-1',
    destChainName: 'injective',
    destChannelId: 'channel-151',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-2016',
    sourcePort: 'transfer',
    destChainId: 'pacific-1',
    destChainName: 'sei',
    destChannelId: 'channel-66',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'pacific-1',
    sourceChainName: 'sei',
    sourceChannelId: 'channel-66',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-2016',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-103',
    sourcePort: 'transfer',
    destChainId: 'pacific-1',
    destChainName: 'sei',
    destChannelId: 'channel-2',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'pacific-1',
    sourceChainName: 'sei',
    sourceChannelId: 'channel-2',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-103',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-39',
    sourcePort: 'transfer',
    destChainId: 'pacific-1',
    destChainName: 'sei',
    destChannelId: 'channel-45',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'pacific-1',
    sourceChainName: 'sei',
    sourceChannelId: 'channel-45',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-39',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'pacific-1',
    sourceChainName: 'sei',
    sourceChannelId: 'channel-11',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-149',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-149',
    sourcePort: 'transfer',
    destChainId: 'pacific-1',
    destChainName: 'sei',
    destChannelId: 'channel-11',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'juno-1',
    sourceChainName: 'juno',
    sourceChannelId: 'channel-20',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-5',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-5',
    sourcePort: 'transfer',
    destChainId: 'juno-1',
    destChainName: 'juno',
    destChannelId: 'channel-20',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'akashnet-2',
    sourceChainName: 'akash',
    sourceChannelId: 'channel-130',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-447',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-447',
    sourcePort: 'transfer',
    destChainId: 'akashnet-2',
    destChainName: 'akash',
    destChannelId: 'channel-130',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-7',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-49',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-49',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-7',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-18',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-191',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-191',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-18',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'evmos_9001-2',
    sourceChainName: 'evmos',
    sourceChannelId: 'channel-13',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-46',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-46',
    sourcePort: 'transfer',
    destChainId: 'evmos_9001-2',
    destChainName: 'evmos',
    destChannelId: 'channel-13',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-11',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-204',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-204',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-11',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-106',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-19',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-19',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-106',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-266',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-324',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-324',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-266',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'atomone-1',
    sourceChainName: 'atomone',
    sourceChannelId: 'channel-3',
    sourcePort: 'transfer',
    destChainId: 'stargaze-1',
    destChainName: 'stargaze',
    destChannelId: 'channel-448',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stargaze-1',
    sourceChainName: 'stargaze',
    sourceChannelId: 'channel-448',
    sourcePort: 'transfer',
    destChainId: 'atomone-1',
    destChainName: 'atomone',
    destChannelId: 'channel-3',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'akashnet-2',
    sourceChainName: 'akash',
    sourceChannelId: 'channel-35',
    sourcePort: 'transfer',
    destChainId: 'juno-1',
    destChainName: 'juno',
    destChannelId: 'channel-29',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'juno-1',
    sourceChainName: 'juno',
    sourceChannelId: 'channel-29',
    sourcePort: 'transfer',
    destChainId: 'akashnet-2',
    destChainName: 'akash',
    destChannelId: 'channel-35',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'juno-1',
    sourceChainName: 'juno',
    sourceChannelId: 'channel-87',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'juno-1',
    destChainName: 'juno',
    destChannelId: 'channel-87',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'juno-1',
    sourceChainName: 'juno',
    sourceChannelId: 'channel-548',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-4328',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-4328',
    sourcePort: 'transfer',
    destChainId: 'juno-1',
    destChainName: 'juno',
    destChannelId: 'channel-548',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'archway-1',
    sourceChainName: 'archway',
    sourceChannelId: 'channel-15',
    sourcePort: 'transfer',
    destChainId: 'juno-1',
    destChainName: 'juno',
    destChannelId: 'channel-290',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'juno-1',
    sourceChainName: 'juno',
    sourceChannelId: 'channel-290',
    sourcePort: 'transfer',
    destChainId: 'archway-1',
    destChainName: 'archway',
    destChannelId: 'channel-15',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-4',
    sourcePort: 'transfer',
    destChainId: 'juno-1',
    destChainName: 'juno',
    destChannelId: 'channel-71',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'juno-1',
    sourceChainName: 'juno',
    sourceChannelId: 'channel-71',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-4',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'juno-1',
    sourceChainName: 'juno',
    sourceChannelId: 'channel-224',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-3',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-3',
    sourcePort: 'transfer',
    destChainId: 'juno-1',
    destChainName: 'juno',
    destChannelId: 'channel-224',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'juno-1',
    sourceChainName: 'juno',
    sourceChannelId: 'channel-139',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-24',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-24',
    sourcePort: 'transfer',
    destChainId: 'juno-1',
    destChainName: 'juno',
    destChannelId: 'channel-139',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'juno-1',
    sourceChainName: 'juno',
    sourceChannelId: 'channel-86',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-2',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-2',
    sourcePort: 'transfer',
    destChainId: 'juno-1',
    destChainName: 'juno',
    destChannelId: 'channel-86',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'akashnet-2',
    sourceChainName: 'akash',
    sourceChannelId: 'channel-63',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-64',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-64',
    sourcePort: 'transfer',
    destChainId: 'akashnet-2',
    destChainName: 'akash',
    destChannelId: 'channel-63',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'akashnet-2',
    sourceChainName: 'akash',
    sourceChannelId: 'channel-109',
    sourcePort: 'transfer',
    destChainId: 'archway-1',
    destChainName: 'archway',
    destChannelId: 'channel-26',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'archway-1',
    sourceChainName: 'archway',
    sourceChannelId: 'channel-26',
    sourcePort: 'transfer',
    destChainId: 'akashnet-2',
    destChainName: 'akash',
    destChannelId: 'channel-109',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'akashnet-2',
    sourceChainName: 'akash',
    sourceChannelId: 'channel-116',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-273',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-273',
    sourcePort: 'transfer',
    destChainId: 'akashnet-2',
    destChainName: 'akash',
    destChannelId: 'channel-116',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-75',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-3',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-3',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-75',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'archway-1',
    sourceChainName: 'archway',
    sourceChannelId: 'channel-11',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-99',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-99',
    sourcePort: 'transfer',
    destChainId: 'archway-1',
    destChainName: 'archway',
    destChannelId: 'channel-11',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-14',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-9',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-9',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-14',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'evmos_9001-2',
    sourceChainName: 'evmos',
    sourceChannelId: 'channel-18',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-23',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-23',
    sourcePort: 'transfer',
    destChainId: 'evmos_9001-2',
    destChainName: 'evmos',
    destChannelId: 'channel-18',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-62',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-2',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-2',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-62',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-32',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-8',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-8',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-32',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'kaiyo-1',
    sourceChainName: 'kujira',
    sourceChannelId: 'channel-5',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-10',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-10',
    sourcePort: 'transfer',
    destChainId: 'kaiyo-1',
    destChainName: 'kujira',
    destChannelId: 'channel-5',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'archway-1',
    sourceChainName: 'archway',
    sourceChannelId: 'channel-61',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-41',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-41',
    sourcePort: 'transfer',
    destChainId: 'archway-1',
    destChainName: 'archway',
    destChannelId: 'channel-61',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-78',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-2',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-2',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-78',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-30',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-18',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-18',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-30',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-8',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-123',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-123',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-8',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'neutron-1',
    sourceChainName: 'neutron',
    sourceChannelId: 'channel-25',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-229',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-229',
    sourcePort: 'transfer',
    destChainId: 'neutron-1',
    destChainName: 'neutron',
    destChannelId: 'channel-25',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'archway-1',
    sourceChainName: 'archway',
    sourceChannelId: 'channel-13',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-111',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-111',
    sourcePort: 'transfer',
    destChainId: 'archway-1',
    destChainName: 'archway',
    destChannelId: 'channel-13',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'archway-1',
    sourceChainName: 'archway',
    sourceChannelId: 'channel-29',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-12',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-12',
    sourcePort: 'transfer',
    destChainId: 'archway-1',
    destChainName: 'archway',
    destChannelId: 'channel-29',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'archway-1',
    sourceChainName: 'archway',
    sourceChannelId: 'channel-50',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-265',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-265',
    sourcePort: 'transfer',
    destChainId: 'archway-1',
    destChainName: 'archway',
    destChannelId: 'channel-50',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'archway-1',
    sourceChainName: 'archway',
    sourceChannelId: 'channel-147',
    sourcePort: 'transfer',
    destChainId: 'beezee-1',
    destChainName: 'beezee',
    destChannelId: 'channel-2',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'beezee-1',
    sourceChainName: 'beezee',
    sourceChannelId: 'channel-2',
    sourcePort: 'transfer',
    destChainId: 'archway-1',
    destChainName: 'archway',
    destChannelId: 'channel-147',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-22',
    sourcePort: 'transfer',
    destChainId: 'evmos_9001-2',
    destChainName: 'evmos',
    destChannelId: 'channel-21',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'evmos_9001-2',
    sourceChainName: 'evmos',
    sourceChannelId: 'channel-21',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-22',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-64',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-69',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-69',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-64',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-11',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-6',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-6',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-11',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'atomone-1',
    sourceChainName: 'atomone',
    sourceChannelId: 'channel-10',
    sourcePort: 'transfer',
    destChainId: 'axelar-dojo-1',
    destChainName: 'axelar',
    destChannelId: 'channel-190',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'axelar-dojo-1',
    sourceChainName: 'axelar',
    sourceChannelId: 'channel-190',
    sourcePort: 'transfer',
    destChainId: 'atomone-1',
    destChainName: 'atomone',
    destChannelId: 'channel-10',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'evmos_9001-2',
    sourceChainName: 'evmos',
    sourceChannelId: 'channel-64',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-7',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-7',
    sourcePort: 'transfer',
    destChainId: 'evmos_9001-2',
    destChainName: 'evmos',
    destChannelId: 'channel-64',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'evmos_9001-2',
    sourceChainName: 'evmos',
    sourceChannelId: 'channel-25',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-9',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-9',
    sourcePort: 'transfer',
    destChainId: 'evmos_9001-2',
    destChainName: 'evmos',
    destChannelId: 'channel-25',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-30',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-253',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-253',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-30',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'beezee-1',
    sourceChainName: 'beezee',
    sourceChannelId: 'channel-3',
    sourcePort: 'transfer',
    destChainId: 'noble-1',
    destChainName: 'noble',
    destChannelId: 'channel-95',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'noble-1',
    sourceChainName: 'noble',
    sourceChannelId: 'channel-95',
    sourcePort: 'transfer',
    destChainId: 'beezee-1',
    destChainName: 'beezee',
    destChannelId: 'channel-3',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'stride-1',
    sourceChainName: 'stride',
    sourceChannelId: 'channel-52',
    sourcePort: 'transfer',
    destChainId: 'phoenix-1',
    destChainName: 'terra2',
    destChannelId: 'channel-46',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'phoenix-1',
    sourceChainName: 'terra2',
    sourceChannelId: 'channel-46',
    sourcePort: 'transfer',
    destChainId: 'stride-1',
    destChainName: 'stride',
    destChannelId: 'channel-52',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'atomone-1',
    sourceChainName: 'atomone',
    sourceChannelId: 'channel-1',
    sourcePort: 'transfer',
    destChainId: 'beezee-1',
    destChainName: 'beezee',
    destChannelId: 'channel-6',
    destPort: 'transfer',
    status: 'UNKNOWN'
  },
  {
    sourceChainId: 'beezee-1',
    sourceChainName: 'beezee',
    sourceChannelId: 'channel-6',
    sourcePort: 'transfer',
    destChainId: 'atomone-1',
    destChainName: 'atomone',
    destChannelId: 'channel-1',
    destPort: 'transfer',
    status: 'UNKNOWN'
  }
];

/**
 * Get IBC channels for a source chain
 */
export function getIBCChannelsForChain(sourceChainName: string): IBCChannelConfig[] {
  return IBC_CHANNELS.filter(c => c.sourceChainName === sourceChainName);
}

/**
 * Get IBC channel between two chains
 */
export function getIBCChannel(sourceChainName: string, destChainName: string): IBCChannelConfig | undefined {
  return IBC_CHANNELS.find(
    c => c.sourceChainName === sourceChainName && c.destChainName === destChainName
  );
}

/**
 * Get IBC channels by chain ID
 */
export function getIBCChannelsForChainId(sourceChainId: string): IBCChannelConfig[] {
  return IBC_CHANNELS.filter(c => c.sourceChainId === sourceChainId);
}
